<template>
  <div class="no-fixed-width-container">
    <div class="title">GOOGLE AUTHENTICATOR</div>
    <div class="divider-line"></div>

    <div class="message first">
      <b>1.&nbsp;</b>Open Google Authenticator App
    </div>
      <div class="download-row">
        <a target="_blank" href="https://itunes.apple.com/us/app/google-authenticator/id388497605">
          <svg-icon class="download" iconClass="download-for-ios"/>
        </a>
        <a
          target="_blank"
          href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2"
        >
          <svg-icon class="download" iconClass="download-for-android"/>
        </a>
      </div>
    <div class="message">
      <b>2.&nbsp;</b>Scan the code below or paste the key into the app
    </div>
    <div class="qrcode-row">
      <vue-qr :text="gaData.qrcode" :size="160" :margin="0"/>
    </div>
    <div class="private-key-row">
      <span class="prop-name">PrivateKey:&nbsp;</span>
      <span id="qrcode">{{ gaData.secret }}</span>
      <el-button
        v-if="copyBtnDisabled"
        type="text"
        class="copy-success"
        data-clipboard-target="#qrcode"
        @click="copyCode"
      >Copy</el-button>
      <span v-else class="copied-style">Copied!</span>
    </div>
    <div class="message">
      <b>3.&nbsp;</b>Enter your verification code generated by Google Authenticator
    </div>

    <el-form autocomplete="on" :model="gaForm" ref="gaForm" label-position="top">
      <div class="security-code-row">
        <security-code v-model="gaForm.gaCode" value blur-on-complete/>
      </div>
      <div class="button-row">
        <el-form-item>
          <el-button
            type="primary"
            :disabled="qrBtnDisabled"
            :loading="loading"
            @click.native.prevent="handleBinding"
            round
          >Next</el-button>
        </el-form-item>
      </div>
    </el-form>
  </div>
</template>

<script>
import Clipboard from "clipboard";

export default {
  data() {
    return {
      gaData: {
        qrcode: "",
        secret: "",
      },
      gaForm: {
        gaCode: "",
      },
      qrBtnDisabled: true,
      copyBtnDisabled: true,
      loading: false,
    };
  },
  watch: {
    "gaForm.gaCode": function(newV, oldV) {
      this.qrBtnDisabled = newV.length !== 6;
      if (newV.length === 6) {
        this.handleBinding();
      }
    },
  },
  created() {
    this.$message.error("First login requires binding to Google authenticator.");
    this.getQrCode();
  },
  methods: {
    copyCode() {
      let clipboard = new Clipboard(".copy-success");
      clipboard.on("success", function(e) {
        e.clearSelection();
      });
      this.copyBtnDisabled = false;
    },
    async getQrCode() {
      this.gaData = await this.$store.dispatch("getGaSecret");
    },
    async handleBinding() {
      try {
        this.loading = true;
        await this.$store.dispatch("bindGa", this.gaForm.gaCode);
        await this.$store.dispatch("getMyInfo");
        this.$message.success("Success");
        this.$router.push({ name: "dashboard" });
      } finally {
        this.loading = false;
      }
    },
  },
};
</script>

<style lang="scss" scoped>
.no-fixed-width-container {
  padding-bottom: 64px;
  background-color: rgba(255, 255, 255, 1);
}

.title {
  margin: 24px 32px;
  font-size: 38px;
  font-family: OpenSans-Light, "PingFang SC", "微软雅黑", sans-serif;
  font-weight: 300;
  color: rgba(74, 144, 226, 1);
  line-height: 52px;
}

.divider-line {
  border: 1px solid rgba(183, 200, 206, 0.5);
  transform: scaleY(0.5);
  transform-origin: 0 100%;
}

.message {
  margin-top: 64px;
  margin-left: 200px;
  font-size: 18px;
  font-family: SourceSansPro-Bold, "PingFang SC", "微软雅黑", sans-serif;
  color: rgba(105, 135, 167, 1);
  line-height: 31px;

  &.first {
    margin-top: 48px;
  }
}

.download-row {
  margin-top: 48px;
  display: flex;
  justify-content: center;

  a:not(:first-child) {
    margin-left: 49px;
  }

  .download {
    width: 158px;
    height: 48px;
  }
}

.qrcode-row {
  margin-top: 48px;
  display: flex;
  justify-content: center;
}

.private-key-row {
  margin-top: 40px;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 16px;
  font-family: SourceSansPro-Regular, "PingFang SC", "微软雅黑", sans-serif;
  font-weight: 400;
  color: rgba(0, 0, 0, 1);
  line-height: 20px;

  .prop-name {
    color: rgba(105, 135, 167, 1);
  }

  .el-button {
    margin-left: 16px;
    font-size: 16px;
  }

  .copied-style {
    margin-left: 16px;
    color: rgba(105, 135, 167, 1);
    font-size: 14px;
  }
}

.security-code-row {
  margin-top: 48px;
  display: flex;
  justify-content: center;

  /deep/ .form-control {
    font-size: 18px !important;
    font-family: OpenSans-Semibold, "PingFang SC", "微软雅黑", sans-serif;
    font-weight: 600;
    color: transparent;
    text-shadow: 0 0 0 rgba(105, 135, 167, 1);
    outline: none;
    border: 1px solid rgba(183, 200, 206, 0.5);

    &:focus {
      background-color: rgba(243, 250, 255, 1);
    }
  }
}

.button-row {
  margin-top: 48px;
  display: flex;
  justify-content: center;

  .el-button {
    width: 141px;
  }
}
</style>
